/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-20 13:11:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005freport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1605662660691L));
    _jspx_dependants.put("jar:file:/C:/psh_java/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/comyPet/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Magz is a HTML5 & CSS3 magazine template is based on Bootstrap 3.\">\r\n");
      out.write("<meta name=\"author\" content=\"Kodinger\">\r\n");
      out.write("<meta name=\"keyword\"\r\n");
      out.write("\tcontent=\"magz, html5, css3, template, magazine template\">\r\n");
      out.write("<!-- Shareable -->\r\n");
      out.write("<meta property=\"og:title\"\r\n");
      out.write("\tcontent=\"HTML5 & CSS3 magazine template is based on Bootstrap 3\" />\r\n");
      out.write("<meta property=\"og:type\" content=\"article\" />\r\n");
      out.write("<meta property=\"og:url\" content=\"http://github.com/nauvalazhar/Magz\" />\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("\tcontent=\"https://raw.githubusercontent.com/nauvalazhar/Magz/master/images/preview.png\" />\r\n");
      out.write("<title>COMYPET &mdash; 신고하기</title>\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/bootstrap/bootstrap.min.css\">\r\n");
      out.write("<!-- IonIcons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/ionicons/css/ionicons.min.css\">\r\n");
      out.write("<!-- Toast -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/toast/jquery.toast.min.css\">\r\n");
      out.write("<!-- OwlCarousel -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/owlcarousel/dist/assets/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/owlcarousel/dist/assets/owl.theme.default.min.css\">\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/magnific-popup/dist/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/resource/scripts/sweetalert/dist/sweetalert.css\">\r\n");
      out.write("<!-- Custom style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resource/css/skins/all.css\">\r\n");
      out.write("<style>\r\n");
      out.write("html, body {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<body class=\"skin-blue\">\r\n");
      out.write("\t<section class=\"home\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"box-wrapper\">\r\n");
      out.write("\t\t\t\t<div class=\"box box-border\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t\t\t<h3>회원 신고</h3>\r\n");
      out.write("\t\t\t\t\t\t<form name=\"repotrForm\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"checkbox-group\" name=\"report\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"비방/욕설\">&nbsp;비방/욕설<br> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"checkbox-group\" name=\"report\" value=\"음란물\">&nbsp;음란물<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"checkbox-group\" name=\"report\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"도배\">&nbsp;도배<br> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"checkbox-group\" name=\"report\" value=\"기타\">&nbsp;기타\r\n");
      out.write("\t\t\t\t\t\t\t\t:\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"reportEtc\" id=\"reportEtc\" readonly\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background-color: #f6f6f6; width: 100%; height: 100%; resize: none;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br> <br>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:report(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_uid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary\">신고</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"javascript:self.close()\" class=\"btn btn-primary\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar textCheck = true;\r\n");
      out.write("\t$(\"input:radio[name=report]\").click(function() {\r\n");
      out.write("\t\tif ($(\"input:radio[name=report]:checked\").val() == \"기타\") {\r\n");
      out.write("\t\t\t$(\"#reportEtc\").attr(\"readonly\", false);\r\n");
      out.write("\t\t\t$(\"#reportEtc\").css(\"background-color\", \"WHITE\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#reportEtc\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#reportEtc\").css(\"background-color\", \"#f6f6f6\");\r\n");
      out.write("\t\t\t$(\"#reportEtc\").val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#reportEtc\").keyup(function() {\r\n");
      out.write("\t\tif ($(\"#reportEtc\").val().length > 20) {\r\n");
      out.write("\t\t\talert(\"신고 내용은 20자까지 가능합니다.\");\r\n");
      out.write("\t\t\ttextCheck = false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\ttextCheck = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\tfunction report(member_uid) {\r\n");
      out.write("\t\tif (textCheck) {\r\n");
      out.write("\t\t\tvar frm = document.repotrForm;\r\n");
      out.write("\t\t\tvar check = $(\"input:radio[name=report]\").is(\":checked\");\r\n");
      out.write("\t\t\tvar report_type = $(\"input:radio[name=report]:checked\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (check) {\r\n");
      out.write("\t\t\t\tif (report_type == \"기타\") {\r\n");
      out.write("\t\t\t\t\treport_type = \"기타:\" + $(\"#reportEtc\").val();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar result = confirm(\"신고 하시겠습니까?\");\r\n");
      out.write("\t\t\t\tconsole.log(report_type);\r\n");
      out.write("\t\t\t\tconsole.log(member_uid);\r\n");
      out.write("\t\t\t\tif (result) {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : \"/MemberReportOk.me\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"writer\" : member_uid,\r\n");
      out.write("\t\t\t\t\t\t\t\"report_type\" : report_type\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tif (data.trim() == \"ok\") {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"신고가 접수되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\twindow.open(\"about:blank\", \"_self\").close();\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"신고 실패, 잠시 후 다시 시도해 주세요.\");\r\n");
      out.write("\t\t\t\t\t\t\twindow.open(\"about:blank\", \"_self\").close();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"신고가 취소되었습니다.\");\r\n");
      out.write("\t\t\t\t\tself.close();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talert(\"신고 유형을 선택해주세요\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /app/member/member_report.jsp(52,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("member_uid");
      // /app/member/member_report.jsp(52,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.member_uid}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
