CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000000;

CREATE TABLE BOARD(
	BOARD_NUM NUMBER(10),
	BOARD_TITLE VARCHAR2(1000),
	BOARD_CONTENTS VARCHAR2(3000),
	BOARD_ID VARCHAR2(50),
	BOARD_DATE DATE,
	CONSTRAINT BOARD_PK PRIMARY KEY (BOARD_NUM),
	CONSTRAINT BOARD_FK FOREIGN KEY (BOARD_ID) REFERENCES "MEMBER" (MEMBER_ID)
);

INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL,'테스트 제목2','테스트 내용','asd',SYSDATE,0);

SELECT * FROM BOARD;

ALTER TABLE BOARD ADD READCOUNT NUMBER(10) DEFAULT 0;
