DROP TABLE "MEMBER";

CREATE TABLE "MEMBER"(
	MEMBER_ID VARCHAR2(50),
	MEMBER_PW VARCHAR2(50),
	MEMBER_NAME VARCHAR2(50),
	MEMBER_AGE NUMBER(2),
	MEMBER_GENDER VARCHAR2(20),
	MEMBER_EMAIL VARCHAR2(50),
	MEMBER_ZIPCODE VARCHAR2(10),
	MEMBER_ADDRESS VARCHAR2(100),
	MEMBER_ADDRESS_DETAIL VARCHAR2(100),
	MEMBER_ADDRESS_ETC VARCHAR2(100),
	CONSTRAINT MEMBER_PK PRIMARY KEY (MEMBER_ID)
);

SELECT * FROM "MEMBER";

SELECT COUNT(*) FROM "MEMBER" WHERE MEMBER_ID = 'ads';

DELETE "MEMBER" ;

SELECT MEMBER_ID FROM MEMBER WHERE MEMBER_ID = 'zxc' AND 
MEMBER_PW ='1112'