CREATE TABLE MEMBER_TASK(
	EMAIL VARCHAR2(50),
	PW VARCHAR2(50),
	NAME VARCHAR2(50),
	CONSTRAINT PK_E PRIMARY KEY (EMAIL)
);

SELECT * FROM MEMBER_TASK;

INSERT INTO MEMBER_TASK VALUES ('asd@naver.com', '@Asdfghjkl1','홍길동');
INSERT INTO MEMBER_TASK VALUES ('qwe@naver.com', '1111');

SELECT COUNT(*) FROM MEMBER_TASK WHERE EMAIL = 'asd@naver.com' AND PW = '1111'

CREATE TABLE HOBBY(
	EMAIL VARCHAR2(50),
	HOBBY VARCHAR2(100),
	CONSTRAINT FK_ID FOREIGN KEY (EMAIL) REFERENCES MEMBER_TASK(EMAIL)
);

DELETE MEMBER_TASK ;
DELETE HOBBY;
DROP TABLE MEMBER_TASK ;
DROP TABLE HOBBY;
SELECT * FROM HOBBY;

