CREATE SEQUENCE CMPP_POP_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;

CREATE TABLE CMPP_POPUP(
	POP_IDX NUMBER,
	POP_TITLE VARCHAR2(100),
	POP_CONTENTS VARCHAR2(3000),
	POP_WRITER NUMBER,
	POP_REGDATE DATE,
	POP_STATE NUMBER(10),
	CONSTRAINTS PK_POP_IDX PRIMARY KEY(POP_IDX),
	CONSTRAINTS FK_POP_UID FOREIGN KEY(POP_WRITER) REFERENCES CMPP_ADMIN_INFO(ADMIN_UID)
);

SELECT * FROM CMPP_POPUP;

