SELECT * FROM (SELECT B.BOARD_TITLE,B.BOARD_IDX,(SELECT NVL(BOARD_PATH, 0) FROM CMPP_BOARD_FILE WHERE BOARD_IDX = B.BOARD_IDX AND ROWNUM = 1) BOARD_PATH
FROM CMPP_PUPPY_BOARD B  WHERE BOARD_BLIND = 0 ORDER BY BOARD_IDX DESC) WHERE ROWNUM <= 16;

SELECT BOARD_PATH FROM CMPP_BOARD_FILE GROUP BY BOARD_IDX;

SELECT *
FROM (
  SELECT BOARD_IDX,
               ROW_NUMBER() OVER( PARTITION BY BOARD_IDX ORDER BY BOARD_IDX ) CNT
  FROM CMPP_BOARD_FILE
  )
WHERE CNT > 1
RANK() OVER()
DENSE_RANK() OVER()

