CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000;

CREATE TABLE "MEMBER"(
	NUM NUMBER NOT NULL,
	NAME VARCHAR2(20),
	BIRTHDAY DATE,
	CONSTRAINT MEMBER_PK PRIMARY KEY(NUM)
);

SELECT * FROM "MEMBER";

INSERT INTO "MEMBER" VALUES(MEMBER_SEQ.NEXTVAL,'한동석',TO_DATE('2000-12-24','YYYY-MM-DD'));