CREATE TABLE "MEMBER"(
	ID VARCHAR2(50),
	NAME VARCHAR2(50),
	PW VARCHAR2(50),
	GENDER VARCHAR2(10),
	ZIPCODE VARCHAR2(10),
	ADDRESS VARCHAR2(200),
	ADDRESS_DETAIL VARCHAR2(200),
	ADDRESS_ETC VARCHAR2(200),
	HP VARCHAR2(20),
	HOBBY VARCHAR2(100),
	CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
	
);

/*CREATE TABLE HOBBY(
	ID VARCHAR2(50),
	HOBBY VARCHAR2(100),
	CONSTRAINT HOBBY_FK FOREIGN KEY (ID) REFERENCES "MEMBER"(ID)
);*/

SELECT * FROM "MEMBER";

SELECT COUNT(*) FROM "MEMBER" WHERE ID='qweqwe' AND PW = '@Asdfghjkl1';