CREATE SEQUENCE CMPP_BOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;

/*공지사항*/
CREATE TABLE CMPP_NOTICE_BOARD(
	BOARD_IDX NUMBER,
	ADMIN_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_NOTICE PRIMARY KEY(BOARD_IDX)
);

/*자유 게시판*/
CREATE TABLE CMPP_FREE_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(100) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_FREE PRIMARY KEY(BOARD_IDX)
);

/*모임 게시판*/
CREATE TABLE CMPP_MEET_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_MEET PRIMARY KEY(BOARD_IDX)
);

/*나눔 게시판*/
CREATE TABLE CMPP_FRA_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_FRA PRIMARY KEY(BOARD_IDX)
);

/*질문 게시판*/
CREATE TABLE CMPP_QNA_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_QNA PRIMARY KEY(BOARD_IDX)
);

/*강아지 갤러리*/
CREATE TABLE CMPP_PUPPY_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_P_GAL PRIMARY KEY(BOARD_IDX)
);

/*고양이 갤러리*/
CREATE TABLE CMPP_CAT_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_C_GAL PRIMARY KEY(BOARD_IDX)
);

/*일상 공유 갤러리*/
CREATE TABLE CMPP_DETAIL_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_D_GAL PRIMARY KEY(BOARD_IDX)
);
/*기타 갤러리*/
CREATE TABLE CMPP_ETC_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_E_GAL PRIMARY KEY(BOARD_IDX)
);

/*불편사항 게시판*/
CREATE TABLE CMPP_SUG_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_CS PRIMARY KEY(BOARD_IDX)
);

/*반려동물 찾기 게시판*/
CREATE TABLE CMPP_LOST_BOARD(
	BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTENTS VARCHAR2(4000) NOT NULL,
	BOARD_READCNT NUMBER,
	BOARD_UP_CNT NUMBER,
	BOARD_DOWN_CNT NUMBER,
	BOARD_REGDATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_BLIND NUMBER(10) DEFAULT 0,
	CONSTRAINTS PK_IDX_LOST PRIMARY KEY(BOARD_IDX)
);

DROP TABLE CMPP_SUG_BOARD; 
DROP TABLE CMPP_FREE_BOARD; 
DROP TABLE CMPP_FRA_BOARD; 
DROP TABLE CMPP_QNA_BOARD; 
DROP TABLE CMPP_MEET_BOARD; 
DROP TABLE CMPP_NOTICE_BOARD; 

DROP TABLE CMPP_LOST_BOARD; 
DROP TABLE CMPP_PUPPY_BOARD; 
DROP TABLE CMPP_ETC_BOARD; 
DROP TABLE CMPP_CAT_BOARD; 
DROP TABLE CMPP_DETAIL_BOARD;

SELECT * FROM CMPP_FREE_BOARD cfb ;

INSERT INTO CMPP_MEET_BOARD VALUES (CMPP_BOARD_SEQ.NEXTVAL,4,'만남게시판 테스트8','아직 없음',0,0,0,to_date(sysdate,'yyyy-MM-dd'),3,0);

SELECT * FROM
(SELECT ROWNUM R, D.*,(SELECT MEMBER_NICK m FROM CMPP_MEMBER_INFO WHERE MEMBER_UID = D.MEMBER_UID)
FROM
(SELECT * FROM CMPP_FREE_BOARD ORDER BY BOARD_IDX DESC) D)B
WHERE B.R BETWEEN 1 AND 10 AND BOARD_BLIND = 0 OR BOARD_BLIND = 1
INSERT INTO CMPP_LOST_BOARD 
VALUES(CMPP_BOARD_SEQ.NEXTVAL, 1,'제목입니다.','제대로 들어갔을까?',0,1,2,'2020-11-10',7,0);
SELECT * FROM CMPP_LOST_BOARD;

CREATE TABLE CMPP_SUP_BOARD(
	CS_IDX NUMBER,
	CS_MANAGER VARCHAR2(20) NOT NULL,
	CS_EMAIL VARCHAR2(50) NOT NULL,
	CS_TEL VARCHAR2(30) NOT NULL,
	CS_CONTENT VARCHAR2(4000) NOT NULL,
	CS_REGDATE DATE NOT NULL,
	CONSTRAINTS PK_SUP PRIMARY KEY(CS_IDX)
);

CREATE TABLE CMPP_ADS_BOARD(
	CS_IDX NUMBER,
	CS_MANAGER VARCHAR2(20) NOT NULL,
	CS_EMAIL VARCHAR2(50) NOT NULL,
	CS_TEL VARCHAR2(30) NOT NULL,
	CS_CONTENT VARCHAR2(4000) NOT NULL,
	CS_REGDATE DATE NOT NULL,
	CONSTRAINTS PK_ADS PRIMARY KEY(CS_IDX)
);

CREATE SEQUENCE CMPP_CS_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;

CREATE SEQUENCE CMPP_UP_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;

CREATE SEQUENCE CMPP_DOWN_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;

DROP TABLE CMPP_BOARD_UP;
DROP TABLE CMPP_BOARD_DOWN;

SELECT * FROM CMPP_SUP_BOARD; 
SELECT * FROM CMPP_ADS_BOARD; 

CREATE TABLE CMPP_BOARD_UP(
	BOARD_UP_IDX NUMBER,
	BOARD_IDX NUMBER NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_UP_RED_DATE DATE NOT NULL,
	CONSTRAINT PK_BOARD_UP PRIMARY KEY (BOARD_UP_IDX),
	CONSTRAINT FK_UP_MEMBER_UID FOREIGN KEY (MEMBER_UID) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);

CREATE TABLE CMPP_BOARD_DOWN(
	BOARD_DOWN_IDX NUMBER,
	BOARD_IDX NUMBER NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_DOWN_RED_DATE DATE NOT NULL,
	CONSTRAINT PK_BOARD_DOWN PRIMARY KEY (BOARD_DOWN_IDX),
	CONSTRAINT FK_DOWN_MEMBER_UID FOREIGN KEY (MEMBER_UID) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);

SELECT * FROM CMPP_MEMBER_INFO;
DROP TABLE CMPP_BOARD_up ;
SELECT * FROM CMPP_BOARD_UP;
INSERT INTO CMPP_BOARD_UP VALUES (CMPP_UP_SEQ.NEXTVAL,39,4,sysdate);

SELECT B.*,(SELECT MEMBER_NICK FROM CMPP_MEMBER_INFO WHERE MEMBER_UID= B.MEMBER_UID) FROM CMPP_MEET_BOARD B WHERE BOARD_IDX = 22