/*관리자 시퀀스*/
CREATE SEQUENCE CMPP_ADMIN_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000;

/*게시판 신고 시퀀스*/
CREATE SEQUENCE CMPP_B_REPORT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000;

/*유저 신고 시퀀스*/
CREATE SEQUENCE CMPP_M_REPORT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000;

/*관리자 정보*/
CREATE TABLE CMPP_ADMIN_INFO(
	ADMIN_UID NUMBER,
	ADMIN_ID VARCHAR2(20) NOT NULL,
	ADMIN_PW VARCHAR2(30) NOT NULL,
	ADMIN_LEVEL NUMBER(10) NOT NULL,
	CONSTRAINTS PK_ADMIN PRIMARY KEY(ADMIN_UID)
);

/*게시글 신고*/
CREATE TABLE CMPP_BOARD_REPORT(
	REPORT_UID NUMBER,
	BOARD_STATE NUMBER NOT NULL,
	BOARD_IDX NUMBER NOT NULL,
	REPORT_TYPE VARCHAR2(100) NOT NULL,
	WRITER NUMBER NOT NULL,
	REPORTER NUMBER NOT NULL,
	REPORT_REG_DATE DATE NOT NULL,
	REPORT_STATE NUMBER,
	CONSTRAINTS PK_REPORT_UID PRIMARY KEY(REPORT_UID),
	CONSTRAINTS FK_WRITER_B FOREIGN KEY(WRITER) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID),
	CONSTRAINTS FK_REPORTER_B FOREIGN KEY(REPORTER) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);
SELECT MEMBER_NICK AS W_NICK, MEMBER_ID AS W_ID, A1.* FROM CMPP_MEMBER_INFO AS A2, 
(SELECT * FROM CMPP_BOARD_REPORT WHERE REPORT_STATE = 1) AS A1 
WHERE A2.MEMER_UID = A1.WRITER;

ALTER TABLE CMPP_BOARD_REPORT ADD CONSTRAINT FK_BOARD_IDX FOREIGN KEY(BOARD_IDX) REFERENCES 
SELECT * FROM CMPP_BOARD_REPORT;

INSERT INTO CMPP_BOARD_REPORT
VALUES(CMPP_B_REPORT_SEQ.NEXTVAL, 3, 1, '비방/욕설', 1,3,sysdate,1);
INSERT INTO CMPP_BOARD_REPORT
VALUES(CMPP_B_REPORT_SEQ.NEXTVAL, 4, 2, '비방/욕설', 2,4,sysdate,1);
INSERT INTO CMPP_BOARD_REPORT
VALUES(CMPP_B_REPORT_SEQ.NEXTVAL, 2, 5, '비방/욕설', 5,6,sysdate,2);
DROP TABLE CMPP_BOARD_REPORT;
/*유저 신고*/
CREATE TABLE CMPP_MEMBER_REPORT(
	REPORT_UID NUMBER,
	REPORTER NUMBER NOT NULL,
	REPORT_TYPE VARCHAR2(500) NOT NULL,
	REPORT_REG_DATE DATE NOT NULL,
	WRITER NUMBER NOT NULL,
	REPORT_STATE NUMBER NOT NULL,
	CONSTRAINTS PK_M_REPORT PRIMARY KEY(REPORT_UID),
	CONSTRAINTS FK_WRITER FOREIGN KEY(WRITER) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID),
	CONSTRAINTS FK_REPORTER FOREIGN KEY(REPORTER) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);
INSERT INTO CMPP_MEMBER_REPORT
VALUES(CMPP_M_REPORT_SEQ.NEXTVAL,1,'기타','2020-11-11',2,1);
INSERT INTO CMPP_MEMBER_REPORT
VALUES(CMPP_M_REPORT_SEQ.NEXTVAL,2,'사기','2020-11-01',3,1);
INSERT INTO CMPP_MEMBER_REPORT
VALUES(CMPP_M_REPORT_SEQ.NEXTVAL,3,'비방/욕설','2020-11-22',4,1);
INSERT INTO CMPP_MEMBER_REPORT
VALUES(CMPP_M_REPORT_SEQ.NEXTVAL,5,'기타','2020-11-21',7,2);
INSERT INTO CMPP_MEMBER_REPORT
VALUES(CMPP_M_REPORT_SEQ.NEXTVAL,6,'기타','2020-11-21',8,1);
INSERT INTO CMPP_MEMBER_REPORT
VALUES(CMPP_M_REPORT_SEQ.NEXTVAL,7,'기타','2020-11-21',8,1);

DROP TABLE CMPP_BO_REPORT;

TRUNCATE TABLE CMPP_MEMBER_REPORT;
SELECT * FROM CMPP_BOARD_REPORT;

SELECT * FROM CMPP_ADMIN_INFO;

ALTER TABLE CMPP_MEMBER_REPORT ADD REPORT_STATE NUMBER;

INSERT INTO CMPP_ADMIN_INFO (CMPP_ADMIN_SEQ.NEXTVAL,'asd','1111',1);
INSERT INTO HR.CMPP_ADMIN_INFO
(ADMIN_UID, ADMIN_ID, ADMIN_PW, ADMIN_LEVEL)
VALUES(CMPP_ADMIN_SEQ.NEXTVAL, 'ASD', '1111', 0);

/*모든 데이터 뽑아오는거*/
SELECT * FROM CMPP_MEMBER_REPORT RE,
(SELECT MEMBER_ID R_ID, MEMBER_NICK R_NICK FROM CMPP_MEMBER_INFO WHERE MEMBER_UID = 1),
(SELECT MEMBER_ID W_ID, MEMBER_NICK W_NICK FROM CMPP_MEMBER_INFO WHERE MEMBER_UID = 2)
WHERE RE.REPORT_UID = 5
ORDER BY REPORT_UID DESC;

SELECT * FROM CMPP_ADMIN_INFO;
SELECT * FROM CMPP_BOARD_REPORT;
DROP TABLE CMPP_BOARD_REPORT ;

SELECT * FROM CMPP_Member_REPORT cbr ;
INSERT INTO CMPP_BOARD_REPORT VALUES (CMPP_B_REPORT_SEQ.NEXTVAL,3,22,'모욕',5,4,sysdate,0);
INSERT INTO HR.CMPP_ADMIN_INFO
(ADMIN_UID, ADMIN_ID, ADMIN_PW, ADMIN_LEVEL)
VALUES(CMPP_ADMIN_SEQ.NEXTVAL, 'ASD', '1111', 0);
SELECT BOARD_TITLE FROM CMPP_FREE_BOARD C, 
(SELECT BOARD_IDX, BOARD_STATE FROM CMPP_BOARD_REPORT) CC
WHERE C.BOARD_IDX = CC.BOARD_IDX;

INSERT INTO CMPP_MEET_BOARD
VALUES(1, 2, '제발 좀 들어가라;;;;', '내용',1,2,3,sysdate,3,1);
INSERT INTO CMPP_FRA_BOARD
VALUES(2, 4, '들어갔으면 좋겠다.', '내용',1,2,3,sysdate,4,1);
VALUES(CMPP_ADMIN_SEQ.NEXTVAL, 'ASD', '1111', 0);

INSERT INTO CMPP_BOARD_REPORT VALUES (CMPP_B_REPORT_SEQ.NEXTVAL,#{board_state},#{board_idx},#{report_type},#{writer},#{reporter},SYSDATE,0,1)
