/*유저 프로필 사진*/
CREATE TABLE CMPP_PROFILE(
	PROFILE_IDX NUMBER,
	FILE_NAME VARCHAR2(100),
	MEMBER_UID NUMBER NOT NULL,
	CONSTRAINTS PK_FILE PRIMARY KEY(PROFILE_IDX),
	CONSTRAINT FK_MEMBER_UID FOREIGN KEY(MEMBER_UID) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);

/*프로필 파일 시퀀스*/
CREATE SEQUENCE CMPP_PROFILE_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;


/*게시판 파일 시퀀스*/
CREATE SEQUENCE CMPP_FILES_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000;


/*게시글 사진*/
CREATE TABLE CMPP_BOARD_FILE(
	FILE_IDX NUMBER,
	FILE_NAME VARCHAR2(100),
	BOARD_PATH VARCHAR2(200),
	BOARD_IDX NUMBER NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	CONSTRAINTS PK_FILES PRIMARY KEY(FILE_IDX)
);

DROP TABLE CMPP_BOARD_FILE;

ALTER TABLE CMPP_PROFILE MODIFY FILE_NAME VARCHAR2 (100) DEFAULT 'defaultProfile.png';

SELECT * FROM CMPP_BOARD_FILE;
DROP TABLE CMPP_PROFILE ;