CREATE SEQUENCE CMPP_MEMBER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000000;

/*유저 정보*/
CREATE TABLE CMPP_MEMBER_INFO(
	MEMBER_UID NUMBER,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_ID VARCHAR2(50) NOT NULL,
	MEMBER_PW VARCHAR2(100) NOT NULL,
	MEMBER_NICK VARCHAR2(20) NOT NULL,
	MEMBER_GENDER VARCHAR2(20) NOT NULL,
	MEMBER_BIRTH DATE NOT NULL,
	MEMBER_TEL VARCHAR2(30) NOT NULL,
	MEMBER_EMAIL VARCHAR2(50) NOT NULL,
	MEMBER_ZIPCODE VARCHAR2(100) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(100) NOT NULL,
	MEMBER_ADDRESS_DETAIL VARCHAR2(100) NOT NULL,
	MEMBER_ADDRESS_ETC VARCHAR2(100) NOT NULL,
	MEMBER_MUTE_COMMENT NUMBER(10) DEFAULT 0 NOT NULL,
	MEMBER_MUTE_CONTENTS NUMBER(10) DEFAULT 0 NOT NULL,
	CONSTRAINTS PK_UID PRIMARY KEY(MEMBER_UID)
);

SELECT * FROM CMPP_MEMBER_INFO;

DROP TABLE CMPP_MEMBER_INFO;

UPDATE CMPP_MEMBER_INFO 
SET MEMBER_PW ='1111'; 

DELETE CMPP_MEMBER_INFO;
