CREATE SEQUENCE CMPP_BOARD_COMMENT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000000000;

CREATE SEQUENCE CMPP_BOARD_RE_COMMENT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1000000000;

/*게시글 댓글*/
CREATE TABLE CMPP_BOARD_COMMENT(
	COMMENT_IDX NUMBER,
	BOARD_IDX NUMBER NOT NULL,
	MEMBER_UID NUMBER NOT NULL,
	COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
	COMMENT_REG_DATE DATE NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	CONSTRAINTS PK_COMMENT_IDX PRIMARY KEY(COMMENT_IDX),
	CONSTRAINTS FK_C_MEMBER_UID FOREIGN KEY(MEMBER_UID) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);

/*게시글 댓글의 답글*/
CREATE TABLE CMPP_RE_COMMENT(
	RE_COMMENT_IDX NUMBER,
	COMMENT_IDX NUMBER NOT NULL,
	BOARD_IDX NUMBER NOT NULL,
	MEMBER_UID NUMBER NOT NULL,
	RE_COMMENT_CONTENT VARCHAR2(4000) NOT NULL,
	RE_COMMENT_REG_DATE DATE NOT NULL,
	CONSTRAINTS PK_RE_COMMENT PRIMARY KEY(RE_COMMENT_IDX),
	CONSTRAINTS FK_UID_RE FOREIGN KEY(MEMBER_UID) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID),
	CONSTRAINTS FK_COMMNET FOREIGN KEY(COMMENT_IDX) REFERENCES CMPP_BOARD_COMMENT(COMMENT_IDX)
);

/*게시글 조회*/
CREATE TABLE CMPP_READ_BOARD(
	READ_BOARD_IDX NUMBER,
	MEMBER_UID NUMBER NOT NULL,
	BOARD_IDX NUMBER NOT NULL,
	BOARD_STATE NUMBER NOT NULL,
	READ_REG_DATE DATE NOT NULL,
	CONSTRAINT PK_READ_BOARD PRIMARY KEY(READ_BOARD_IDX),
	CONSTRAINT FK_READ_UID FOREIGN KEY (MEMBER_UID) REFERENCES CMPP_MEMBER_INFO(MEMBER_UID)
);

DELETE CMPP_BOARD_COMMENT WHERE COMMENT_IDX = 12;

DROP TABLE CMPP_RE_COMMENT; 
DELETE CMPP_BOARD_COMMENT ;
SELECT * FROM CMPP_BOARD_COMMENT cbc ;
SELECT B.*, (SELECT MEMBER_NICK FROM CMPP_MEMBER_INFO WHERE MEMBER_UID = B.MEMBER_UID) member_nick FROM CMPP_BOARD_COMMENT B WHERE BOARD_IDX = 22 ORDER BY COMMENT_IDX DESC;
INSERT INTO CMPP_RE_COMMENT VALUES (CMPP_BOARD_RE_COMMENT_SEQ.NEXTVAL,9,4,'asd',SYSDATE);