CREATE TABLE MEMBER_TASK(
	EMAIL VARCHAR2(50),
	PW VARCHAR2(50),
	NAME VARCHAR2(50),
	CONSTRAINT PK_E PRIMARY KEY (EMAIL)
);

SELECT * FROM MEMBER_TASK;

CREATE TABLE HOBBY(
	EMAIL VARCHAR2(50),
	HOBBY VARCHAR2(100),
	CONSTRAINT FK_ID FOREIGN KEY (EMAIL) REFERENCES MEMBER_TASK(EMAIL)
);

SELECT * FROM HOBBY;

